import { MPRecord, ProjectRecord, AuditRiskItem, ComplaintRecord, ActionQueueItem, UserProfile } from '../src/types';

export const initialUsers: UserProfile[] = [
  {
    uid: 'demo-mp-01',
    name: 'Dr. A. Senthilkumar',
    email: 'mp.dharmapuri@sansad.nic.in',
    role: 'MP',
    state: 'Tamil Nadu',
    district: 'Dharmapuri',
    constituency: 'Dharmapuri',
    designation: 'Member of Parliament (Lok Sabha)',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    createdAt: '2024-06-05T10:00:00Z',
    lastLogin: new Date().toISOString(),
    isDemo: true,
  },
  {
    uid: 'demo-admin-01',
    name: 'Rajesh Kumar Verma, IAS',
    email: 'admin.mplads@nic.in',
    role: 'ADMIN',
    designation: 'Joint Secretary (MPLADS Division), MoSPI',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    createdAt: '2024-01-10T09:00:00Z',
    lastLogin: new Date().toISOString(),
    isDemo: true,
  },
  {
    uid: 'demo-district-01',
    name: 'K. Shanthi, IAS',
    email: 'dm.dharmapuri@tn.gov.in',
    role: 'DISTRICT_OFFICER',
    state: 'Tamil Nadu',
    district: 'Dharmapuri',
    constituency: 'Dharmapuri',
    designation: 'District Collector & District Magistrate',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    createdAt: '2024-02-15T11:00:00Z',
    lastLogin: new Date().toISOString(),
    isDemo: true,
  },
  {
    uid: 'demo-agency-01',
    name: 'Er. V. Murugan',
    email: 'ee.pwd.dharmapuri@tn.gov.in',
    role: 'IMPLEMENTING_AGENCY',
    state: 'Tamil Nadu',
    district: 'Dharmapuri',
    designation: 'Executive Engineer, PWD (Buildings & Roads)',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    createdAt: '2024-03-01T08:30:00Z',
    lastLogin: new Date().toISOString(),
    isDemo: true,
  },
  {
    uid: 'demo-auditor-01',
    name: 'Sunita Sharma, IA&AS',
    email: 'auditor.cag@cag.gov.in',
    role: 'AUDITOR',
    designation: 'Senior Audit Officer, CAG Field Inspection Unit',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    createdAt: '2024-02-20T10:00:00Z',
    lastLogin: new Date().toISOString(),
    isDemo: true,
  },
  {
    uid: 'demo-citizen-01',
    name: 'P. Arumugam',
    email: 'arumugam.pennagaram@gmail.com',
    role: 'CITIZEN',
    state: 'Tamil Nadu',
    district: 'Dharmapuri',
    constituency: 'Dharmapuri',
    designation: 'Resident & Gram Panchayat Member',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    status: 'active',
    createdAt: '2024-04-12T14:20:00Z',
    lastLogin: new Date().toISOString(),
    isDemo: true,
  },
];

export const initialMps: MPRecord[] = [
  {
    id: 'mp-tn-dharmapuri',
    name: 'Dr. A. Senthilkumar',
    displayName: 'Dr. A. Senthilkumar',
    party: 'DMK',
    constituency: 'Dharmapuri',
    state: 'Tamil Nadu',
    house: 'Lok Sabha',
    membershipStatus: 'Sitting',
    term: '18th Lok Sabha (2024 - Present)',
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&auto=format&fit=crop&q=80',
    officialProfileUrl: 'https://sansad.in/ls/members/biography/5120',
    source: 'Lok Sabha Official Portal / Verified Public Record',
    lastUpdated: '2025-02-15T00:00:00Z',
    isLive: true,
    contactEmail: 'senthil.kumar@sansad.nic.in',
    contactOffice: 'Collectorate Complex, Dharmapuri - 636705',
    stats: {
      totalProjects: 48,
      sanctionedAmountLakhs: 485.5,
      utilizedAmountLakhs: 392.2,
      completedProjects: 31,
      inProgressProjects: 14,
      delayedProjects: 3,
      entitlementLakhs: 500.0,
    },
    fundUtilization: {
      allocatedAmountLakhs: 500.0,
      sanctionedAmountLakhs: 485.5,
      utilizedAmountLakhs: 392.2,
      recommendedWorksCount: 48,
      completedWorksCount: 31,
      ongoingWorksCount: 14,
    },
    email: 'senthil.kumar@sansad.nic.in',
    phone: '+91-4342-230500',
  },
  {
    id: 'mp-up-varanasi',
    name: 'Narendra Modi',
    displayName: 'Shri Narendra Modi',
    party: 'BJP',
    constituency: 'Varanasi',
    state: 'Uttar Pradesh',
    house: 'Lok Sabha',
    membershipStatus: 'Sitting',
    term: '18th Lok Sabha (2024 - Present)',
    photo: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&auto=format&fit=crop&q=80',
    officialProfileUrl: 'https://sansad.in/ls/members/biography/4589',
    source: 'Lok Sabha Official Portal / Verified Public Record',
    lastUpdated: '2025-02-20T00:00:00Z',
    isLive: true,
    contactEmail: 'modi.office@sansad.nic.in',
    contactOffice: 'Ravindrapuri Parliamentary Office, Varanasi - 221005',
    stats: {
      totalProjects: 72,
      sanctionedAmountLakhs: 500.0,
      utilizedAmountLakhs: 478.4,
      completedProjects: 58,
      inProgressProjects: 12,
      delayedProjects: 2,
      entitlementLakhs: 500.0,
    },
    fundUtilization: {
      allocatedAmountLakhs: 500.0,
      sanctionedAmountLakhs: 500.0,
      utilizedAmountLakhs: 478.4,
      recommendedWorksCount: 72,
      completedWorksCount: 58,
      ongoingWorksCount: 12,
    },
    email: 'modi.office@sansad.nic.in',
    phone: '+91-542-2220100',
  },
  {
    id: 'mp-up-raebareli',
    name: 'Rahul Gandhi',
    displayName: 'Shri Rahul Gandhi',
    party: 'INC',
    constituency: 'Rae Bareli',
    state: 'Uttar Pradesh',
    house: 'Lok Sabha',
    membershipStatus: 'Sitting',
    term: '18th Lok Sabha (2024 - Present)',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80',
    officialProfileUrl: 'https://sansad.in/ls/members/biography/4060',
    source: 'Lok Sabha Official Portal / Verified Public Record',
    lastUpdated: '2025-02-18T00:00:00Z',
    isLive: true,
    contactEmail: 'rahul.gandhi@sansad.nic.in',
    contactOffice: 'Feroze Gandhi Colony, Rae Bareli - 229001',
    stats: {
      totalProjects: 54,
      sanctionedAmountLakhs: 460.0,
      utilizedAmountLakhs: 375.0,
      completedProjects: 36,
      inProgressProjects: 15,
      delayedProjects: 3,
      entitlementLakhs: 500.0,
    },
    fundUtilization: {
      allocatedAmountLakhs: 500.0,
      sanctionedAmountLakhs: 460.0,
      utilizedAmountLakhs: 375.0,
      recommendedWorksCount: 54,
      completedWorksCount: 36,
      ongoingWorksCount: 15,
    },
    email: 'rahul.gandhi@sansad.nic.in',
    phone: '+91-535-2200222',
  },
  {
    id: 'mp-ka-bangaloresouth',
    name: 'Tejasvi Surya',
    displayName: 'Shri Tejasvi Surya',
    party: 'BJP',
    constituency: 'Bangalore South',
    state: 'Karnataka',
    house: 'Lok Sabha',
    membershipStatus: 'Sitting',
    term: '18th Lok Sabha (2024 - Present)',
    photo: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&auto=format&fit=crop&q=80',
    officialProfileUrl: 'https://sansad.in/ls/members/biography/5104',
    source: 'Lok Sabha Official Portal / Verified Public Record',
    lastUpdated: '2025-02-12T00:00:00Z',
    isLive: true,
    contactEmail: 'tejasvi.surya@sansad.nic.in',
    contactOffice: 'Jayanagar 4th Block, Bengaluru - 560011',
    stats: {
      totalProjects: 63,
      sanctionedAmountLakhs: 490.0,
      utilizedAmountLakhs: 440.5,
      completedProjects: 49,
      inProgressProjects: 11,
      delayedProjects: 3,
      entitlementLakhs: 500.0,
    },
    fundUtilization: {
      allocatedAmountLakhs: 500.0,
      sanctionedAmountLakhs: 490.0,
      utilizedAmountLakhs: 440.5,
      recommendedWorksCount: 63,
      completedWorksCount: 49,
      ongoingWorksCount: 11,
    },
    email: 'tejasvi.surya@sansad.nic.in',
    phone: '+91-80-26567890',
  },
  {
    id: 'mp-mh-baramati',
    name: 'Supriya Sule',
    displayName: 'Smt. Supriya Sule',
    party: 'NCP (Sharadchandra Pawar)',
    constituency: 'Baramati',
    state: 'Maharashtra',
    house: 'Lok Sabha',
    membershipStatus: 'Sitting',
    term: '18th Lok Sabha (2024 - Present)',
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=300&auto=format&fit=crop&q=80',
    officialProfileUrl: 'https://sansad.in/ls/members/biography/4260',
    source: 'Lok Sabha Official Portal / Verified Public Record',
    lastUpdated: '2025-02-14T00:00:00Z',
    isLive: true,
    contactEmail: 'supriya.sule@sansad.nic.in',
    contactOffice: 'Vidyanagari, Baramati, Pune - 413133',
    stats: {
      totalProjects: 51,
      sanctionedAmountLakhs: 470.0,
      utilizedAmountLakhs: 410.0,
      completedProjects: 39,
      inProgressProjects: 9,
      delayedProjects: 3,
      entitlementLakhs: 500.0,
    },
    fundUtilization: {
      allocatedAmountLakhs: 500.0,
      sanctionedAmountLakhs: 470.0,
      utilizedAmountLakhs: 410.0,
      recommendedWorksCount: 51,
      completedWorksCount: 39,
      ongoingWorksCount: 9,
    },
    email: 'supriya.sule@sansad.nic.in',
    phone: '+91-2112-224400',
  },
  {
    id: 'mp-mp-indore',
    name: 'Shankar Lalwani',
    displayName: 'Shri Shankar Lalwani',
    party: 'BJP',
    constituency: 'Indore',
    state: 'Madhya Pradesh',
    house: 'Lok Sabha',
    membershipStatus: 'Sitting',
    term: '18th Lok Sabha (2024 - Present)',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&auto=format&fit=crop&q=80',
    officialProfileUrl: 'https://sansad.in/ls/members/biography/5115',
    source: 'Lok Sabha Official Portal / Verified Public Record',
    lastUpdated: '2025-02-19T00:00:00Z',
    isLive: true,
    contactEmail: 'shankar.lalwani@sansad.nic.in',
    contactOffice: 'MG Road, Residency Area, Indore - 452001',
    stats: {
      totalProjects: 59,
      sanctionedAmountLakhs: 495.0,
      utilizedAmountLakhs: 462.8,
      completedProjects: 45,
      inProgressProjects: 12,
      delayedProjects: 2,
      entitlementLakhs: 500.0,
    },
    fundUtilization: {
      allocatedAmountLakhs: 500.0,
      sanctionedAmountLakhs: 495.0,
      utilizedAmountLakhs: 462.8,
      recommendedWorksCount: 59,
      completedWorksCount: 45,
      ongoingWorksCount: 12,
    },
    email: 'shankar.lalwani@sansad.nic.in',
    phone: '+91-731-2521100',
  },
];

export const initialProjects: ProjectRecord[] = [
  {
    id: 'proj-tn-dhm-01',
    code: 'MPLADS/2024-25/TN-DHM/001',
    title: 'Solar Powered Reverse Osmosis (RO) Drinking Water Plant at Pennagaram GHSS',
    description: 'Installation of a 1000 LPH community RO drinking water filtration plant powered by a 5kW rooftop solar PV array to supply safe fluorosis-free water to 1,200 rural school students and surrounding villagers.',
    category: 'Drinking Water',
    mpId: 'mp-tn-dharmapuri',
    mpName: 'Dr. A. Senthilkumar',
    state: 'Tamil Nadu',
    district: 'Dharmapuri',
    constituency: 'Dharmapuri',
    block: 'Pennagaram',
    village: 'Pennagaram Town Panchayat',
    pincode: '636810',
    department: 'Rural Development & Panchayat Raj',
    implementingAgency: 'TWAD Board & BDO Pennagaram',
    coordinates: { lat: 12.1332, lng: 77.8872 },
    financial: {
      recommendedAmountLakhs: 18.5,
      sanctionedAmountLakhs: 18.5,
      releasedAmountLakhs: 18.5,
      expenditureLakhs: 18.5,
      balanceLakhs: 0.0,
    },
    status: 'Completed',
    progressPercentage: 100,
    timeline: [
      { status: 'Proposed', date: '2024-06-20', note: 'Recommended by MP based on Gram Sabha fluorosis petition', updatedBy: 'MP Nodal Staff' },
      { status: 'Verified', date: '2024-07-05', note: 'Feasibility inspection approved by District Collector', updatedBy: 'DRDA Officer' },
      { status: 'Sanctioned', date: '2024-07-22', note: 'Administrative sanction accorded vide AS/1402/2024', updatedBy: 'District Collector' },
      { status: 'In Progress', date: '2024-08-10', note: 'Civil foundations and RO machinery delivered on site', updatedBy: 'TWAD Engineer' },
      { status: 'Completed', date: '2024-11-14', note: 'Water quality lab test certified (TDS 110 ppm, Fluoride < 0.8 mg/L)', updatedBy: 'Executive Engineer' },
    ],
    evidence: [
      {
        id: 'ev-1',
        stage: 'Before',
        url: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=600&auto=format&fit=crop&q=80',
        description: 'Site inspection prior to civil foundation work showing dilapidated hand pump.',
        date: '2024-07-08',
        uploadedBy: 'Assistant Engineer, TWAD',
        gpsLocation: { lat: 12.1331, lng: 77.8871 },
      },
      {
        id: 'ev-2',
        stage: 'During',
        url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
        description: 'Installation of stainless steel storage tanks and solar panel mounts.',
        date: '2024-09-15',
        uploadedBy: 'Site Supervisor, PWD',
        gpsLocation: { lat: 12.1332, lng: 77.8872 },
      },
      {
        id: 'ev-3',
        stage: 'Current / After',
        url: 'https://images.unsplash.com/photo-1517646287270-a5a9ca602e5c?w=600&auto=format&fit=crop&q=80',
        description: 'Operational plant dispensing chilled purified water to school students.',
        date: '2024-11-15',
        uploadedBy: 'Headmaster, GHSS Pennagaram',
        gpsLocation: { lat: 12.1333, lng: 77.8873 },
      },
    ],
    documents: [
      { id: 'doc-1', name: 'Administrative Sanction Order AS/1402/2024.pdf', type: 'Sanction Order', status: 'Available', uploadDate: '2024-07-25', fileSize: '1.4 MB' },
      { id: 'doc-2', name: 'Work Order WO/TWAD/2024/09.pdf', type: 'Work Order', status: 'Available', uploadDate: '2024-08-01', fileSize: '850 KB' },
      { id: 'doc-3', name: 'Utilization Certificate UC_DHM_001.pdf', type: 'Utilization Certificate', status: 'Available', uploadDate: '2024-12-05', fileSize: '420 KB' },
      { id: 'doc-4', name: 'Physical Completion Certificate CC_001.pdf', type: 'Completion Certificate', status: 'Available', uploadDate: '2024-12-10', fileSize: '910 KB' },
      { id: 'doc-5', name: 'Water Quality Inspection & CAG Audit Report.pdf', type: 'Inspection Report', status: 'Available', uploadDate: '2025-01-15', fileSize: '2.1 MB' },
    ],
    transparencyScore: 98,
    riskScore: 12,
    riskCategory: 'LOW',
    year: '2024-25',
    lastUpdated: '2025-01-18T10:00:00Z',
    source: 'SIH DEMO DATA',
    convergenceScheme: 'Jal Jeevan Mission (JJM convergence)',
  },
  {
    id: 'proj-tn-dhm-02',
    code: 'MPLADS/2024-25/TN-DHM/002',
    title: 'Construction of All-Weather Paver Block Link Road to Sitheri Tribal Hamlet',
    description: 'Laying of a 2.4 km heavy-duty interlocked paver block road connecting Sitheri hill village to the main Harur ghat road, ensuring emergency ambulance transit.',
    category: 'Road Construction',
    mpId: 'mp-tn-dharmapuri',
    mpName: 'Dr. A. Senthilkumar',
    state: 'Tamil Nadu',
    district: 'Dharmapuri',
    constituency: 'Dharmapuri',
    block: 'Harur',
    village: 'Sitheri Hill Village',
    pincode: '636903',
    department: 'Highways & Rural Works',
    implementingAgency: 'DRDA Engineering Wing',
    coordinates: { lat: 11.9167, lng: 78.4333 },
    financial: {
      recommendedAmountLakhs: 45.0,
      sanctionedAmountLakhs: 45.0,
      releasedAmountLakhs: 30.0,
      expenditureLakhs: 26.5,
      balanceLakhs: 15.0,
    },
    status: 'In Progress',
    progressPercentage: 68,
    timeline: [
      { status: 'Proposed', date: '2024-07-10', note: 'Submitted following tribal community representation', updatedBy: 'MP' },
      { status: 'Sanctioned', date: '2024-08-20', note: 'Forest clearance NOC obtained', updatedBy: 'Collector' },
      { status: 'In Progress', date: '2024-09-28', note: 'Sub-base grading completed, paver laying in progress', updatedBy: 'Executive Engineer' },
    ],
    evidence: [
      {
        id: 'ev-4',
        stage: 'Before',
        url: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=600&auto=format&fit=crop&q=80',
        description: 'Mud road washed away during monsoon prior to execution.',
        date: '2024-07-15',
        uploadedBy: 'Village Administrative Officer',
        gpsLocation: { lat: 11.9165, lng: 78.4331 },
      },
      {
        id: 'ev-5',
        stage: 'During',
        url: 'https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=600&auto=format&fit=crop&q=80',
        description: 'Paver blocks laying at km 1.4 on the hairpin bend.',
        date: '2025-01-20',
        uploadedBy: 'DRDA Supervisor',
        gpsLocation: { lat: 11.9168, lng: 78.4335 },
      },
    ],
    documents: [
      { id: 'doc-6', name: 'Forest Department NOC & AS Order.pdf', type: 'Sanction Order', status: 'Available', uploadDate: '2024-08-22', fileSize: '3.2 MB' },
      { id: 'doc-7', name: 'Contract Agreement & Work Order.pdf', type: 'Work Order', status: 'Available', uploadDate: '2024-09-05', fileSize: '1.8 MB' },
      { id: 'doc-8', name: 'Interim Utilization Certificate Phase 1.pdf', type: 'Utilization Certificate', status: 'Available', uploadDate: '2024-12-15', fileSize: '780 KB' },
      { id: 'doc-9', name: 'Third Party Quality Audit Stage 2.pdf', type: 'Inspection Report', status: 'Needs Verification', uploadDate: '2025-01-22', fileSize: '1.1 MB' },
    ],
    transparencyScore: 92,
    riskScore: 28,
    riskCategory: 'LOW',
    year: '2024-25',
    lastUpdated: '2025-02-01T14:30:00Z',
    source: 'SIH DEMO DATA',
    convergenceScheme: 'PMGSY (Pradhan Mantri Gram Sadak Yojana convergence)',
  },
  {
    id: 'proj-tn-dhm-03',
    code: 'MPLADS/2023-24/TN-DHM/019',
    title: 'Multi-Purpose Community Hall & Skill Center at Karimangalam',
    description: 'Construction of an 8,000 sq ft RCC community hall with women SHG training center and digital library.',
    category: 'Community Hall',
    mpId: 'mp-tn-dharmapuri',
    mpName: 'Dr. A. Senthilkumar',
    state: 'Tamil Nadu',
    district: 'Dharmapuri',
    constituency: 'Dharmapuri',
    block: 'Karimangalam',
    village: 'Karimangalam Town',
    pincode: '635111',
    department: 'Town Panchayats',
    implementingAgency: 'District Rural Development Agency',
    coordinates: { lat: 12.3082, lng: 78.2045 },
    financial: {
      recommendedAmountLakhs: 35.0,
      sanctionedAmountLakhs: 35.0,
      releasedAmountLakhs: 35.0,
      expenditureLakhs: 35.0,
      balanceLakhs: 0.0,
    },
    status: 'Completed',
    progressPercentage: 100,
    timeline: [
      { status: 'Proposed', date: '2023-09-12', note: 'Public utility hall demand', updatedBy: 'MP' },
      { status: 'Sanctioned', date: '2023-11-04', note: 'AS sanctioned by Collector', updatedBy: 'Collector' },
      { status: 'In Progress', date: '2024-01-15', note: 'Roof slab cast', updatedBy: 'DRDA' },
      { status: 'Completed', date: '2024-08-30', note: 'Inaugurated and handed over to Town Panchayat', updatedBy: 'Executive Officer' },
    ],
    evidence: [
      {
        id: 'ev-6',
        stage: 'Before',
        url: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=600&auto=format&fit=crop&q=80',
        description: 'Barren poramboke land before excavation.',
        date: '2023-11-10',
        uploadedBy: 'Karimangalam EO',
      },
      {
        id: 'ev-7',
        stage: 'Current / After',
        url: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=600&auto=format&fit=crop&q=80',
        description: 'Completed air-cooled community hall hosting vocational workshop.',
        date: '2024-09-02',
        uploadedBy: 'Karimangalam EO',
      },
    ],
    documents: [
      { id: 'doc-10', name: 'Sanction_Order_Karimangalam.pdf', type: 'Sanction Order', status: 'Available' },
      { id: 'doc-11', name: 'Final_Utilization_Certificate.pdf', type: 'Utilization Certificate', status: 'Available' },
      { id: 'doc-12', name: 'Completion_Certificate_Signed.pdf', type: 'Completion Certificate', status: 'Available' },
    ],
    transparencyScore: 96,
    riskScore: 18,
    riskCategory: 'LOW',
    year: '2023-24',
    lastUpdated: '2024-09-05T09:15:00Z',
    source: 'SIH DEMO DATA',
  },
  {
    id: 'proj-tn-dhm-04',
    code: 'MPLADS/2024-25/TN-DHM/042',
    title: 'Modern Science & STEM Innovation Lab at Government Boys HSS Palacode',
    description: 'Establishment of a digital science lab, robotic kits, physics demonstration benches, and high-speed internet lab for rural secondary students.',
    category: 'School Building',
    mpId: 'mp-tn-dharmapuri',
    mpName: 'Dr. A. Senthilkumar',
    state: 'Tamil Nadu',
    district: 'Dharmapuri',
    constituency: 'Dharmapuri',
    block: 'Palacode',
    village: 'Palacode Town',
    pincode: '636808',
    department: 'School Education Department',
    implementingAgency: 'Public Works Department (Buildings)',
    coordinates: { lat: 12.2981, lng: 78.0776 },
    financial: {
      recommendedAmountLakhs: 22.0,
      sanctionedAmountLakhs: 22.0,
      releasedAmountLakhs: 18.0,
      expenditureLakhs: 14.8,
      balanceLakhs: 7.2,
    },
    status: 'In Progress',
    progressPercentage: 75,
    timeline: [
      { status: 'Proposed', date: '2024-08-05', note: 'Proposed under Education upliftment initiative', updatedBy: 'MP' },
      { status: 'Sanctioned', date: '2024-09-12', note: 'Technical sanction approved', updatedBy: 'Collector' },
      { status: 'In Progress', date: '2024-10-20', note: 'Lab furniture and equipment installed, electrical wiring pending', updatedBy: 'EE PWD' },
    ],
    evidence: [
      {
        id: 'ev-8',
        stage: 'Before',
        url: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=600&auto=format&fit=crop&q=80',
        description: 'Old unused store room before renovation.',
        date: '2024-09-20',
        uploadedBy: 'Principal GBHSS',
      },
      {
        id: 'ev-9',
        stage: 'During',
        url: 'https://images.unsplash.com/photo-1562774053-701939374585?w=600&auto=format&fit=crop&q=80',
        description: 'Workstations set up with digital microscopes and 3D printing equipment.',
        date: '2025-01-15',
        uploadedBy: 'PWD Site Engineer',
      },
    ],
    documents: [
      { id: 'doc-13', name: 'Palacode_STEM_Sanction.pdf', type: 'Sanction Order', status: 'Available' },
      { id: 'doc-14', name: 'Work_Order_PWD_EDN_2024.pdf', type: 'Work Order', status: 'Available' },
      { id: 'doc-15', name: 'Phase_1_UC.pdf', type: 'Utilization Certificate', status: 'Available' },
    ],
    transparencyScore: 94,
    riskScore: 22,
    riskCategory: 'LOW',
    year: '2024-25',
    lastUpdated: '2025-01-25T11:00:00Z',
    source: 'SIH DEMO DATA',
    convergenceScheme: 'Samagra Shiksha Abhiyan convergence',
  },
  {
    id: 'proj-tn-dhm-05',
    code: 'MPLADS/2023-24/TN-DHM/088',
    title: 'Underground Drainage & Sanitation Facility at Nallampalli Bus Stand',
    description: 'Construction of modern eco-san public sanitation complex with bio-digester tank and solar lighting.',
    category: 'Sanitation',
    mpId: 'mp-tn-dharmapuri',
    mpName: 'Dr. A. Senthilkumar',
    state: 'Tamil Nadu',
    district: 'Dharmapuri',
    constituency: 'Dharmapuri',
    block: 'Nallampalli',
    village: 'Nallampalli',
    pincode: '636807',
    department: 'Rural Development',
    implementingAgency: 'BDO Nallampalli',
    coordinates: { lat: 12.0456, lng: 78.1421 },
    financial: {
      recommendedAmountLakhs: 16.0,
      sanctionedAmountLakhs: 16.0,
      releasedAmountLakhs: 16.0,
      expenditureLakhs: 16.0,
      balanceLakhs: 0.0,
    },
    status: 'Completed',
    progressPercentage: 100,
    timeline: [
      { status: 'Proposed', date: '2023-10-01', note: 'Public hygiene petition', updatedBy: 'MP' },
      { status: 'Sanctioned', date: '2023-11-20', note: 'Sanction issued', updatedBy: 'Collector' },
      { status: 'Completed', date: '2024-04-15', note: 'Handed over to Panchayat', updatedBy: 'BDO' },
    ],
    evidence: [
      {
        id: 'ev-10',
        stage: 'Before',
        url: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=600&auto=format&fit=crop&q=80',
        description: 'Open waste area beside bus stand.',
        date: '2023-11-25',
        uploadedBy: 'Panchayat Secretary',
      },
      {
        id: 'ev-11',
        stage: 'Current / After',
        url: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=600&auto=format&fit=crop&q=80',
        description: 'Commissioned sanitation complex with disabled access ramps.',
        date: '2024-04-20',
        uploadedBy: 'BDO Nallampalli',
      },
    ],
    documents: [
      { id: 'doc-16', name: 'Sanction_Order.pdf', type: 'Sanction Order', status: 'Available' },
      { id: 'doc-17', name: 'UC_Certificate.pdf', type: 'Utilization Certificate', status: 'Available' },
      { id: 'doc-18', name: 'Completion_Cert.pdf', type: 'Completion Certificate', status: 'Available' },
    ],
    transparencyScore: 97,
    riskScore: 15,
    riskCategory: 'LOW',
    year: '2023-24',
    lastUpdated: '2024-04-25T16:00:00Z',
    source: 'SIH DEMO DATA',
    convergenceScheme: 'Swachh Bharat Mission (Grameen) convergence',
  },
  {
    id: 'proj-tn-dhm-06',
    code: 'MPLADS/2024-25/TN-DHM/104',
    title: 'Primary Health Sub-Center (HSC) Upgradation & Cold Chain Room at Morappur',
    description: 'Construction of cold chain vaccine storage room, emergency maternal transit beds, and doctors consultation cabin at Morappur Primary Health Center.',
    category: 'Health & Family Welfare',
    mpId: 'mp-tn-dharmapuri',
    mpName: 'Dr. A. Senthilkumar',
    state: 'Tamil Nadu',
    district: 'Dharmapuri',
    constituency: 'Dharmapuri',
    block: 'Morappur',
    village: 'Morappur Town',
    pincode: '635305',
    department: 'Health & Family Welfare',
    implementingAgency: 'Public Works Department (Medical Wing)',
    coordinates: { lat: 12.1891, lng: 78.3842 },
    financial: {
      recommendedAmountLakhs: 28.0,
      sanctionedAmountLakhs: 28.0,
      releasedAmountLakhs: 20.0,
      expenditureLakhs: 16.4,
      balanceLakhs: 11.6,
    },
    status: 'Delayed',
    progressPercentage: 58,
    timeline: [
      { status: 'Proposed', date: '2024-04-10', note: 'Maternal health facility expansion', updatedBy: 'MP' },
      { status: 'Sanctioned', date: '2024-05-25', note: 'Administrative approval accorded', updatedBy: 'Collector' },
      { status: 'In Progress', date: '2024-07-15', note: 'Structure erected up to lintel level', updatedBy: 'PWD' },
      { status: 'Delayed', date: '2024-12-01', note: 'Contractor dispute over price escalation of medical grade flooring', updatedBy: 'District Collector' },
    ],
    evidence: [
      {
        id: 'ev-12',
        stage: 'Before',
        url: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=600&auto=format&fit=crop&q=80',
        description: 'Dilapidated tiled shed holding vaccine refrigerators on backup generator.',
        date: '2024-05-10',
        uploadedBy: 'Medical Officer, Morappur',
      },
      {
        id: 'ev-13',
        stage: 'During',
        url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600&auto=format&fit=crop&q=80',
        description: 'Lintel construction paused; raw brickwork exposed.',
        date: '2024-11-20',
        uploadedBy: 'Junior Engineer PWD',
      },
    ],
    documents: [
      { id: 'doc-19', name: 'Health_Sanction_Morappur.pdf', type: 'Sanction Order', status: 'Available' },
      { id: 'doc-20', name: 'Work_Order_Medical_PWD.pdf', type: 'Work Order', status: 'Available' },
      { id: 'doc-21', name: 'Inspection_Notice_To_Contractor.pdf', type: 'Inspection Report', status: 'Needs Verification' },
      { id: 'doc-22', name: 'Utilization_Certificate_Interim.pdf', type: 'Utilization Certificate', status: 'Missing' },
    ],
    transparencyScore: 82,
    riskScore: 74,
    riskCategory: 'HIGH',
    year: '2024-25',
    lastUpdated: '2025-02-10T12:00:00Z',
    source: 'SIH DEMO DATA',
    convergenceScheme: 'National Health Mission (NHM) infrastructure grant',
  },
  {
    id: 'proj-up-vns-01',
    code: 'MPLADS/2024-25/UP-VNS/001',
    title: 'Solar High-Mast Lighting and Pedestrian Ghat Safety Corridor at Dashashwamedh',
    description: 'Installation of 8 solar powered high-mast LED towers and automated distress panic alarms along the ghat approach promenade.',
    category: 'Non-Conventional Energy',
    mpId: 'mp-up-varanasi',
    mpName: 'Shri Narendra Modi',
    state: 'Uttar Pradesh',
    district: 'Varanasi',
    constituency: 'Varanasi',
    block: 'Kashi Kshetra',
    village: 'Dashashwamedh Ghat Area',
    pincode: '221001',
    department: 'Urban Development',
    implementingAgency: 'Varanasi Smart City Ltd & UPNEDA',
    coordinates: { lat: 25.3076, lng: 83.0104 },
    financial: {
      recommendedAmountLakhs: 25.0,
      sanctionedAmountLakhs: 25.0,
      releasedAmountLakhs: 25.0,
      expenditureLakhs: 25.0,
      balanceLakhs: 0.0,
    },
    status: 'Completed',
    progressPercentage: 100,
    timeline: [
      { status: 'Proposed', date: '2024-06-15', note: 'Pilgrim and tourist safety upgrade', updatedBy: 'MP Representative' },
      { status: 'Sanctioned', date: '2024-07-10', note: 'Sanctioned by DM Varanasi', updatedBy: 'DM Varanasi' },
      { status: 'Completed', date: '2024-10-25', note: 'All high masts illuminated and integrated with Smart City Command Center', updatedBy: 'CEO Smart City' },
    ],
    evidence: [
      {
        id: 'ev-14',
        stage: 'Before',
        url: 'https://images.unsplash.com/photo-1561361513-2d000a50f0dc?w=600&auto=format&fit=crop&q=80',
        description: 'Dim approach pathway prior to high-mast lighting.',
        date: '2024-06-25',
        uploadedBy: 'UPNEDA Engineer',
      },
      {
        id: 'ev-15',
        stage: 'Current / After',
        url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=600&auto=format&fit=crop&q=80',
        description: 'Illuminated promenade with active solar storage battery banks.',
        date: '2024-11-02',
        uploadedBy: 'Varanasi Smart City Field Officer',
      },
    ],
    documents: [
      { id: 'doc-23', name: 'Varanasi_Solar_AS.pdf', type: 'Sanction Order', status: 'Available' },
      { id: 'doc-24', name: 'Completion_Certificate_VNS.pdf', type: 'Completion Certificate', status: 'Available' },
      { id: 'doc-25', name: 'Final_UC_VNS_001.pdf', type: 'Utilization Certificate', status: 'Available' },
    ],
    transparencyScore: 99,
    riskScore: 8,
    riskCategory: 'LOW',
    year: '2024-25',
    lastUpdated: '2024-11-05T08:00:00Z',
    source: 'SIH DEMO DATA',
  },
  {
    id: 'proj-up-rbl-01',
    code: 'MPLADS/2024-25/UP-RBL/009',
    title: 'Installation of Deep Borewell and Overhead Tank at Lalganj Community Health Center',
    description: 'Providing dedicated 24x7 water supply infrastructure to the maternity ward and inpatient units of Lalganj CHC.',
    category: 'Drinking Water',
    mpId: 'mp-up-raebareli',
    mpName: 'Shri Rahul Gandhi',
    state: 'Uttar Pradesh',
    district: 'Rae Bareli',
    constituency: 'Rae Bareli',
    block: 'Lalganj',
    village: 'Lalganj CHC Premises',
    pincode: '229206',
    department: 'UP Jal Nigam & Health',
    implementingAgency: 'UP Jal Nigam (Rural)',
    coordinates: { lat: 26.1667, lng: 80.9667 },
    financial: {
      recommendedAmountLakhs: 20.0,
      sanctionedAmountLakhs: 20.0,
      releasedAmountLakhs: 15.0,
      expenditureLakhs: 13.2,
      balanceLakhs: 6.8,
    },
    status: 'In Progress',
    progressPercentage: 70,
    timeline: [
      { status: 'Proposed', date: '2024-07-20', note: 'Hospital water shortage crisis', updatedBy: 'MP' },
      { status: 'Sanctioned', date: '2024-08-30', note: 'Sanction approved by CDO', updatedBy: 'CDO Rae Bareli' },
      { status: 'In Progress', date: '2024-10-15', note: 'Borewell drilled to 180m, staging of tank ongoing', updatedBy: 'Jal Nigam EE' },
    ],
    evidence: [
      {
        id: 'ev-16',
        stage: 'Before',
        url: 'https://images.unsplash.com/photo-1541888946425-d0fbb18086f6?w=600&auto=format&fit=crop&q=80',
        description: 'Dry water storage tank at hospital premises.',
        date: '2024-08-01',
        uploadedBy: 'Superintendent Lalganj CHC',
      },
      {
        id: 'ev-17',
        stage: 'During',
        url: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80',
        description: 'RCC staging column shuttering in progress.',
        date: '2025-01-10',
        uploadedBy: 'Jal Nigam Junior Engineer',
      },
    ],
    documents: [
      { id: 'doc-26', name: 'Sanction_Order_Lalganj.pdf', type: 'Sanction Order', status: 'Available' },
      { id: 'doc-27', name: 'Work_Order_Jal_Nigam.pdf', type: 'Work Order', status: 'Available' },
      { id: 'doc-28', name: 'Stage_1_UC.pdf', type: 'Utilization Certificate', status: 'Available' },
    ],
    transparencyScore: 91,
    riskScore: 24,
    riskCategory: 'LOW',
    year: '2024-25',
    lastUpdated: '2025-01-15T15:00:00Z',
    source: 'SIH DEMO DATA',
  },
  {
    id: 'proj-ka-blr-01',
    code: 'MPLADS/2024-25/KA-BLRS/014',
    title: 'Rainwater Harvesting Recharge Wells & Green Lake Buffer at Yediyur Lake',
    description: 'Construction of 25 ground percolation recharge wells and bio-retention swales to arrest urban flooding in South Bengaluru.',
    category: 'Irrigation & Flood Control',
    mpId: 'mp-ka-bangaloresouth',
    mpName: 'Shri Tejasvi Surya',
    state: 'Karnataka',
    district: 'Bengaluru Urban',
    constituency: 'Bangalore South',
    block: 'Jayanagar',
    village: 'Yediyur Ward',
    pincode: '560070',
    department: 'BBMP Lakes Division',
    implementingAgency: 'BBMP Engineering Wing',
    coordinates: { lat: 12.9288, lng: 77.5756 },
    financial: {
      recommendedAmountLakhs: 30.0,
      sanctionedAmountLakhs: 30.0,
      releasedAmountLakhs: 30.0,
      expenditureLakhs: 28.5,
      balanceLakhs: 1.5,
    },
    status: 'Completed',
    progressPercentage: 98,
    timeline: [
      { status: 'Proposed', date: '2024-05-18', note: 'Urban flood prevention priority', updatedBy: 'MP' },
      { status: 'Sanctioned', date: '2024-06-25', note: 'Sanctioned by Special Commissioner', updatedBy: 'DC Urban' },
      { status: 'Completed', date: '2024-11-20', note: 'Wells operational during winter rains', updatedBy: 'Chief Engineer BBMP' },
    ],
    evidence: [
      {
        id: 'ev-18',
        stage: 'Before',
        url: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=600&auto=format&fit=crop&q=80',
        description: 'Eroded lake bund and stagnant storm drain runoff.',
        date: '2024-06-02',
        uploadedBy: 'BBMP Lakes AE',
      },
      {
        id: 'ev-19',
        stage: 'Current / After',
        url: 'https://images.unsplash.com/photo-1517646287270-a5a9ca602e5c?w=600&auto=format&fit=crop&q=80',
        description: 'Percolation pits filtering rainwater into aquifer bed.',
        date: '2024-11-25',
        uploadedBy: 'BBMP Lakes Executive Engineer',
      },
    ],
    documents: [
      { id: 'doc-29', name: 'BBMP_AS_Order_2024.pdf', type: 'Sanction Order', status: 'Available' },
      { id: 'doc-30', name: 'Hydrological_Survey_Report.pdf', type: 'Inspection Report', status: 'Available' },
      { id: 'doc-31', name: 'Final_UC_BBMP.pdf', type: 'Utilization Certificate', status: 'Available' },
    ],
    transparencyScore: 97,
    riskScore: 14,
    riskCategory: 'LOW',
    year: '2024-25',
    lastUpdated: '2024-12-01T10:00:00Z',
    source: 'SIH DEMO DATA',
  },
];

export const initialAuditRisks: AuditRiskItem[] = [
  {
    id: 'risk-01',
    projectId: 'proj-tn-dhm-06',
    projectCode: 'MPLADS/2024-25/TN-DHM/104',
    projectTitle: 'Primary Health Sub-Center (HSC) Upgradation & Cold Chain Room at Morappur',
    location: 'Morappur, Dharmapuri, Tamil Nadu',
    riskScore: 74,
    level: 'HIGH',
    factors: [
      'Progress reported 58% but no physical evidence uploaded for 82 days',
      'Contractor dispute flagged in site logs',
      'Interim Utilization Certificate missing',
      'Milestone deadline exceeded by 65 days',
    ],
    reason: 'Reported expenditure of ₹16.4 Lakhs with stagnant site progress and unverified contractor variation claims.',
    evidenceSummary: 'Latest image uploaded in November 2024 shows incomplete masonry without lintel curing certs.',
    source: 'Automated Exception Engine & CAG Field Audit Scanner',
    timestamp: '2025-02-14T11:20:00Z',
    suggestedAction: 'Issue physical site inspection notice to District Collector & suspend next installment release pending reconciliation.',
    status: 'Open',
  },
  {
    id: 'risk-02',
    projectId: 'proj-tn-dhm-02',
    projectCode: 'MPLADS/2024-25/TN-DHM/002',
    projectTitle: 'Construction of All-Weather Paver Block Link Road to Sitheri Tribal Hamlet',
    location: 'Sitheri, Harur, Tamil Nadu',
    riskScore: 42,
    level: 'MEDIUM',
    factors: [
      'Potential partial overlap with State Tribal Welfare Department road proposal (STW-2023-89)',
      'Third-party quality report marked as Needs Verification',
    ],
    reason: 'Scheme convergence verification required to rule out duplicate billing of hill retaining wall segment.',
    evidenceSummary: 'GPS coordinates of km 1.8 align within 45 meters of previously sanctioned STW culvert.',
    source: 'GIS Overlap Detection Engine',
    timestamp: '2025-02-12T16:45:00Z',
    suggestedAction: 'Hold final tranche release; request joint certification from DRDA and Tribal Welfare Department.',
    status: 'Reviewed',
  },
  {
    id: 'risk-03',
    projectId: 'proj-tn-dhm-04',
    projectCode: 'MPLADS/2024-25/TN-DHM/042',
    projectTitle: 'Modern Science & STEM Innovation Lab at Government Boys HSS Palacode',
    location: 'Palacode, Dharmapuri, Tamil Nadu',
    riskScore: 28,
    level: 'LOW',
    factors: [
      'Minor delay in electrical connection compliance',
      'Equipment serial numbers awaiting asset registry tagging',
    ],
    reason: 'Vendor delivered lab hardware; fire safety inspection document pending upload.',
    evidenceSummary: 'Photos confirm delivery and unboxing of scientific models.',
    source: 'Document Completeness Monitor',
    timestamp: '2025-02-10T09:10:00Z',
    suggestedAction: 'Prompt Implementing Agency to upload Fire NOC and Asset Tag ledger.',
    status: 'Open',
  },
];

export const initialComplaints: ComplaintRecord[] = [
  {
    id: 'comp-01',
    trackingId: 'MPLADS-GRV-2025-0012',
    citizenName: 'P. Arumugam',
    citizenEmail: 'arumugam.pennagaram@gmail.com',
    citizenPhone: '+91 94432 18902',
    problemTitle: 'RO Drinking Water Plant dispenser nozzle broken and TDS meter uncalibrated',
    description: 'The solar RO plant at Pennagaram GHSS has developed a leak in the student dispensing valve and the filter display shows replacement warning for membrane.',
    category: 'Drinking Water',
    severity: 'Medium',
    location: {
      state: 'Tamil Nadu',
      district: 'Dharmapuri',
      constituency: 'Dharmapuri',
      village: 'Pennagaram',
      lat: 12.1332,
      lng: 77.8872,
    },
    possibleLevel: 'District',
    matchedProjectIds: ['proj-tn-dhm-01'],
    status: 'Assigned',
    assignedOfficer: 'K. Shanthi, IAS (District Collector)',
    assignedAgency: 'TWAD Board Dharmapuri',
    createdAt: '2025-02-10T14:20:00Z',
    updatedAt: '2025-02-11T16:00:00Z',
    timeline: [
      { status: 'Submitted', timestamp: '2025-02-10T14:20:00Z', note: 'Complaint submitted via Citizen AI Assistant' },
      { status: 'Under Review', timestamp: '2025-02-11T09:30:00Z', note: 'Reviewed by District Nodal Grievance Cell', officer: 'Grievance Officer' },
      { status: 'Assigned', timestamp: '2025-02-11T16:00:00Z', note: 'Sent to TWAD Maintenance Engineer for warranty servicing', officer: 'District Collector' },
    ],
  },
  {
    id: 'comp-02',
    trackingId: 'MPLADS-GRV-2025-0019',
    citizenName: 'Meenakshi Sundaram',
    citizenEmail: 'meenakshi.s@outlook.com',
    problemTitle: 'No street lighting along newly constructed community hall approach road',
    description: 'The community hall at Karimangalam is very useful but the 300 meter connecting lane lacks lights, creating safety hazards for women returning from evening SHG meetings.',
    category: 'Community Hall',
    severity: 'Low',
    location: {
      state: 'Tamil Nadu',
      district: 'Dharmapuri',
      constituency: 'Dharmapuri',
      village: 'Karimangalam',
      lat: 12.3082,
      lng: 78.2045,
    },
    possibleLevel: 'Local',
    matchedProjectIds: ['proj-tn-dhm-03'],
    status: 'Under Review',
    createdAt: '2025-02-15T11:00:00Z',
    updatedAt: '2025-02-15T11:00:00Z',
    timeline: [
      { status: 'Submitted', timestamp: '2025-02-15T11:00:00Z', note: 'Grievance logged by citizen' },
      { status: 'Under Review', timestamp: '2025-02-15T11:30:00Z', note: 'Assigned to Town Panchayat Executive Officer for inspection' },
    ],
  },
];

export const initialActionQueue: ActionQueueItem[] = [
  {
    id: 'act-01',
    type: 'NEW_RECOMMENDATION',
    projectId: 'proj-prop-01',
    title: 'Installation of 50 Solar Street Lights in Morappur Town & Station Road',
    mpName: 'Dr. A. Senthilkumar',
    constituency: 'Dharmapuri',
    amountLakhs: 14.5,
    submittedDate: '2025-02-16',
    priority: 'Normal',
    aiPrecheckStatus: 'PROCEED',
  },
  {
    id: 'act-02',
    type: 'PENDING_VERIFICATION',
    projectId: 'proj-prop-02',
    title: 'Borewell & Overhead Tank at Pennagaram Weekly Shandy Market',
    mpName: 'Dr. A. Senthilkumar',
    constituency: 'Dharmapuri',
    amountLakhs: 19.0,
    submittedDate: '2025-02-14',
    priority: 'High',
    aiPrecheckStatus: 'POSSIBLE DUPLICATE / OVERLAP',
    flagReason: 'AI detected 91% similarity with existing TWAD rural water supply work 120m away.',
  },
  {
    id: 'act-03',
    type: 'DELAYED_WORK',
    projectId: 'proj-tn-dhm-06',
    title: 'Primary Health Sub-Center (HSC) Upgradation & Cold Chain Room at Morappur',
    mpName: 'Dr. A. Senthilkumar',
    constituency: 'Dharmapuri',
    amountLakhs: 28.0,
    submittedDate: '2024-05-25',
    priority: 'High',
    flagReason: 'Work delayed by >60 days; contractor contract re-tender notice pending.',
  },
];

export const actionQueue = initialActionQueue;
export const auditRisks = initialAuditRisks;
export const complaints = initialComplaints;
export const mps = initialMps;
export const projects = initialProjects;
export const users = initialUsers;
